[package]
name = "quincy-quinn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Quinn
quinn = { version = "^0.9", features = ["runtime-tokio"] }

# Interfaces and networking
tokio-tun = "^0.7"
socket2 = "^0.4"
bytes = "^1.4"
etherparse = "^0.13"

# Tokio and futures
tokio = { version = "^1.25", features = ["rt-multi-thread", "macros", "sync", "io-util", "fs"] }
futures = "^0.3"
futures-util = "^0.3"
dashmap = "^5"

# Configuration
figment = { version = "^0.10", features = ["toml", "env"] }
serde = { version = "^1.0", features = ["derive"] }

# TLS
rustls = { version = "^0.20" }
rustls-pemfile = "^1.0"
rcgen = "^0.10"
webpki = "^0.22"

# Tracing/Logging
tracing = "^0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Utils
anyhow = "^1.0"
rand = "^0.8"
delegate = "^0.9"
clap = { version = "^4.1", features = ["derive"] }
once_cell = "^1.17"
