[package]
name = "quincy"
version = "0.1.1"
authors = ["Jakub Kubík <jakub.kubik.it@protonmail.com>"]
license = "MIT"
description = "QUIC-based VPN"
readme = "README.md"
homepage = "https://github.com/M0dEx/quincy"
repository = "https://github.com/M0dEx/quincy"
keywords = ["vpn", "quic"]
categories = ["command-line-utilities", "network-programming"]
edition = "2021"

[lib]
name = "quincy"

[dependencies]
# Quinn
quinn = "^0.10.1"

# Interfaces and networking
tun = { version = "^0.5.5", features = ["async"] }
socket2 = "^0.5.2"
bytes = "^1.4"
etherparse = "^0.13.0"
ipnet = "^2.7"
libc = "^0.2.144"

# Tokio and futures
tokio = { version = "^1.25", features = ["rt-multi-thread", "macros", "sync", "io-util", "fs"] }
futures = "^0.3.28"
futures-util = "^0.3.28"
dashmap = "^5.4"

# Configuration
figment = { version = "^0.10.8", features = ["toml", "env"] }
serde = { version = "^1.0", features = ["derive"] }

# TLS
rustls = "^0.21.1"
rustls-pemfile = "^1.0"
rcgen = "^0.10.0"
webpki = "^0.22.0"

# Authentication
argon2 = "^0.5.0"
rand_chacha = "^0.3.1"
rpassword = "^7.2"

# Tracing/Logging
tracing = "^0.1.37"
tracing-subscriber = { version = "^0.3.17", features = ["env-filter"] }

# Utils
bincode = "^2.0.0-rc.3"
chrono = { version = "^0.4.24", features = ["clock"] }
getset = "^0.1.2"
anyhow = "^1.0"
delegate = "^0.9.0"
clap = { version = "^4.1", features = ["derive"] }
once_cell = "^1.17"

[dev-dependencies]
tokio-test = "^0.4.2"
