[package]
name = "quincy-quinn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-tun = "^0.7.0"
anyhow = "^1.0.22"
quinn = { version = "^0.9.0", features = ["runtime-tokio"] }
rcgen = "^0.10.0"
futures-util = "^0.3.25"
tracing = "^0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
rustls = { version = "^0.20.6", default-features = false, features = ["dangerous_configuration"] }
rustls-pemfile = "^1.0.1"
socket2 = "^0.4"
webpki = "^0.22"
clap = { version = "^4.0.10", features = ["derive"] }
tokio = { version = "^1.21.2", features = ["rt-multi-thread", "macros", "sync", "io-util"] }
bytes = "^1.2.1"