[package]
name = "quincy-quinn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Quinn
quinn = { version = "^0.9.0", features = ["runtime-tokio"] }

# Interfaces and networking
tokio-tun = "^0.7.0"
socket2 = "^0.4"
bytes = "^1.2.1"

# Tokio and futures
tokio = { version = "^1.24", features = ["rt-multi-thread", "macros", "sync", "io-util", "fs"] }
futures-util = "^0.3.25"

# Configuration
figment = { version = "^0.10", features = ["toml", "env"] }
serde = { version = "^1.0", features = ["derive"] }

# TLS
rustls = { version = "^0.20.6", default-features = false, features = ["dangerous_configuration"] }
rustls-pemfile = "^1.0.1"
rcgen = "^0.10.0"
webpki = "^0.22"

# Tracing/Logging
tracing = "^0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

# Utils
anyhow = "^1.0.22"
clap = { version = "^4.1", features = ["derive"] }
once_cell = "^1.17.0"
