[package]
name = "quincy"
version = "0.1.0"
authors = ["Jakub Kubík <jakub.kubik.it@protonmail.com>"]
license = "MIT"
description = "QUIC-based VPN"
readme = "README.md"
homepage = "https://github.com/M0dEx/quincy"
repository = "https://github.com/M0dEx/quincy"
keywords = ["vpn", "quic"]
categories = ["command-line-utilities", "network-programming"]
edition = "2021"

[lib]
name = "quincy"

[dependencies]
# Quinn
quinn = { version = "^0.9", features = ["runtime-tokio"] }

# Interfaces and networking
tun = { version = "^0.5", features = ["async"] }
socket2 = "^0.5"
bytes = "^1.4"
etherparse = "^0.13"
ipnet = "^2.7"
libc = "^0.2"

# Tokio and futures
tokio = { version = "^1.25", features = ["rt-multi-thread", "macros", "sync", "io-util", "fs"] }
futures = "^0.3"
futures-util = "^0.3"
dashmap = "^5"

# Configuration
figment = { version = "^0.10", features = ["toml", "env"] }
serde = { version = "^1.0", features = ["derive"] }

# TLS
rustls = "^0.20"
rustls-pemfile = "^1.0"
rcgen = "^0.10"
webpki = "^0.22"

# Authentication
argon2 = "^0.5"
rand_chacha = "^0.3"
rpassword = "^7.2"

# Tracing/Logging
tracing = "^0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Utils
bincode = "^2.0.0-rc.3"
chrono = { version = "^0.4", features = ["clock"] }
getset = "^0.1"
anyhow = "^1.0"
delegate = "^0.9"
clap = { version = "^4.1", features = ["derive"] }
once_cell = "^1.17"

[dev-dependencies]
tokio-test = "^0.4"
