# The address and port the Quincy server is available at
connection_string = "quincy:55555"

[authentication]
# The username used for authentication
username = "test"
# The password used for authentication
password = "test"
# A list of trusted certificates the server can use or have its certificate signed by
trusted_certificates = ["examples/cert/ca_cert.pem"]

[connection]
# The MTU used by the QUIC tunnel and the spawned TUN interface
mtu = 1400

[network]
routes = [
    "10.0.1.0/24",
    "10.11.12.0/24"
]
dns_servers = [
    "10.0.0.1"
]

[log]
# The log level
level = "info"
