name: Publish release

on:
  release:
    types: [created]

jobs:
  publish-crate:
    name: Publish crate

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: dtolnay/rust-toolchain@nightly
        name: Set up toolchain
      - uses: Swatinem/rust-cache@v2
        name: Cache toolchain and dependencies
      - uses: katyo/publish-crates@v2
        name: Publish crate
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  build-linux-binaries:
    name: Build x86_64 Linux binaries

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: dtolnay/rust-toolchain@nightly
        name: Set up toolchain
      - uses: Swatinem/rust-cache@v2
        name: Cache toolchain and dependencies
      - name: Build x86_64 Linux binaries
        run: |
          cargo build --release -F jemalloc
          mkdir ./quincy-linux-x86_64
          cp target/release/quincy-client quincy-linux-x86_64/
          cp target/release/quincy-server quincy-linux-x86_64/
          cp target/release/quincy-users quincy-linux-x86_64/
          tar zcf quincy-linux-x86_64.tar.gz -C quincy-linux-x86_64 .
      - uses: softprops/action-gh-release@v1
        name: Add binary to release
        with:
          files: |
            quincy-linux-x86_64.tar.gz

  build-macos-binaries:
    name: Build arm64 macOS binaries

    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: dtolnay/rust-toolchain@nightly
        name: Set up toolchain
      - uses: Swatinem/rust-cache@v2
        name: Cache toolchain and dependencies
      - name: Build arm64 macOS binaries
        run: |
          cargo build --release -F jemalloc
          mkdir ./quincy-macos-arm64
          cp target/release/quincy-client quincy-macos-arm64/
          cp target/release/quincy-server quincy-macos-arm64/
          cp target/release/quincy-users quincy-macos-arm64/
          tar zcf quincy-macos-arm64.tar.gz -C quincy-macos-arm64 .
      - uses: softprops/action-gh-release@v1
        name: Add binary to release
        with:
          files: |
            quincy-macos-arm64.tar.gz

  build-windows-binaries:
    name: Build x86_64 Windows binaries

    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: dtolnay/rust-toolchain@nightly
        name: Set up toolchain
      - uses: Swatinem/rust-cache@v2
        name: Cache toolchain and dependencies
      - uses: ilammy/setup-nasm@v1
        name: Install NASM
      - name: Build x86_64 Windows binaries
        run: |
          cargo build --release
          Invoke-WebRequest https://www.wintun.net/builds/wintun-0.14.1.zip -OutFile wintun.zip
          7z x wintun.zip
          mkdir ./quincy-windows-x86_64
          cp wintun/bin/amd64/wintun.dll quincy-windows-x86_64/
          cp target/release/quincy-client.exe quincy-windows-x86_64/
          cp target/release/quincy-server.exe quincy-windows-x86_64/
          cp target/release/quincy-users.exe quincy-windows-x86_64/
          7z a quincy-windows-x86_64.zip quincy-windows-x86_64
      - uses: softprops/action-gh-release@v1
        name: Add binary to release
        with:
          files: |
            quincy-windows-x86_64.zip

  build-docker-image:
    name: Build Docker image

    runs-on: ubuntu-latest

    strategy:
      matrix:
        crypto:
          - standard
          - quantum
    steps:
      - uses: docker/setup-qemu-action@v3
        name: Set up QEMU
      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx
      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        name: Build and push
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            FEATURES=crypto-${{ matrix.crypto }},jemalloc
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/quincy:${{ startsWith(matrix.crypto, 'standard') && github.ref_name || format('{0}-{1}', github.ref_name, matrix.crypto) }}
            ${{ vars.DOCKERHUB_USERNAME }}/quincy:${{ startsWith(matrix.crypto, 'standard') && 'latest' || format('latest-{0}', matrix.crypto) }}
