name: Publish release

on:
  release:
    types: [created]

jobs:
  publish-crate:
    name: Publish crate

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - uses: dtolnay/rust-toolchain@stable
        name: Set up toolchain
      - uses: Swatinem/rust-cache@v2
        name: Cache toolchain and dependencies
      - uses: katyo/publish-crates@v2
        name: Publish crate
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  build-linux-binaries:
    name: Build x86_64 Linux binaries

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - uses: dtolnay/rust-toolchain@stable
        name: Set up toolchain
      - uses: Swatinem/rust-cache@v2
        name: Cache toolchain and dependencies
      - name: Build x86_64 Linux binaries
        run: |
          cargo build --release
          mkdir ./quincy-linux-x86_64
          cp target/release/quincy-client quincy-linux-x86_64/
          cp target/release/quincy-server quincy-linux-x86_64/
          cp target/release/quincy-users quincy-linux-x86_64/
          tar zcf quincy-linux-x86_64.tar.gz -C quincy-linux-x86_64 .
      - uses: softprops/action-gh-release@v1
        name: Add binary to release
        with:
          files: |
            quincy-linux-x86_64.tar.gz
